### ISSUE TITLE
Easy way to post requests?

### ISSUE THREAD

**Issue by hardikaecor** [joskolenberg/laravel-jory#17]
Thanks for the amazing package, saves a lot of time in terms of getting data from server. But just wanted to confirm if I can make post/patch/delete requests such easily to server with this package? If yes how?

**Comment by joskolenberg** [comment]
Hey @hardikaecor 

Thanks for your support.

This package was built for fetching data only.

Have been thinking about it posting data though, but I guess that would be a separate package only for basic create, update and delete logic.
But that would involve a lot custom logic on validation, authorizing etc. and I'm not sure if that would all fit into a package without it becoming more complex than the original problem it tries to solve.

So no plans for the near future and still working on the laravel-jory 2.0 version in my rare spare time for now.
So maybe someday in the future 😁, I'll keep you posted then.
